baseURL: https://tobiaskisch.ch
theme: hugobricks
defaultContentLanguage: en
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false
    permalinks:
      page:
        posts: /blog/:slug
        services: /services/:slug
      section:
        posts: /blog/
        services: /services/
