baseURL: https://tobiaskisch.ch
theme: hugobricks
defaultContentLanguage: en
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false
    permalinks:
      page:
        posts: /blog/:slug
        services: /services/:slug
      section:
        posts: /blog/
        services: /services/

params:
  opengraph_io_api_key: 4269ddb3-03d8-4a81-9f8c-a5303a5e0790

enableRobotsTXT: true

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
