[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.115.0"
  
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''

